"""
export_to_c.py

Chạy sau train_tiny.py:
    python export_to_c.py

Output: model_weights.h — copy vào thư mục sketch Arduino

RLIF thêm các tensor so với LIF thường:
  rlif1.recurrent.weight  : (FC1_UNITS, FC1_UNITS) — V trong U[t+1]=βU[t]+I[t]+V·S[t]
  rlif1.recurrent.bias    : (FC1_UNITS,)
  rlif2.V                 : (NUM_CLASSES,) — elementwise (all_to_all=False)
  rlif1.threshold         : scalar learnable
  rlif2.threshold         : scalar learnable
  rlif1.beta / rlif2.beta : scalar learnable
"""

import torch
import numpy as np
from model_tiny  import KWS_SNN_Tiny
from config_tiny import Config


def quantize_int8(tensor):
    t    = tensor.detach().numpy().flatten().astype(np.float32)
    tmin, tmax = float(t.min()), float(t.max())
    scale = (tmax - tmin) / 255.0 + 1e-9
    zp    = int(round(-tmin / scale))
    zp    = max(0, min(255, zp))
    q     = np.clip(np.round(t / scale + zp), 0, 255).astype(np.uint8)
    return q, scale, zp


def write_tensor(name, tensor, f):
    data, scale, zp = quantize_int8(tensor)
    size      = len(data)
    shape_str = "x".join(str(s) for s in tensor.shape)
    f.write(f"// {name}  [{shape_str}]  scale={scale:.8f}  zp={zp}\n")
    f.write(f"static const float   {name}_scale = {scale:.8f}f;\n")
    f.write(f"static const int     {name}_zp    = {zp};\n")
    f.write(f"static const int     {name}_size  = {size};\n")
    f.write(f"static const uint8_t {name}[{size}] PROGMEM = {{\n  ")
    for i, v in enumerate(data):
        f.write(f"0x{v:02X}")
        if i < size - 1:
            f.write(", ")
            if (i + 1) % 16 == 0:
                f.write("\n  ")
    f.write("\n};\n\n")


def write_scalar(name, value, f):
    f.write(f"static const float {name} = {value:.8f}f;\n")


def export():
    print("=== Loading checkpoint ===")
    ckpt = torch.load("checkpoints/tiny_best.pth", map_location="cpu",
                      weights_only=False)
    saved_cfg = ckpt.get("config", {})

    checks = [("CONV1_CH", Config.CONV1_CH), ("CONV2_CH", Config.CONV2_CH),
              ("FC1_UNITS", Config.FC1_UNITS), ("FLATTEN_SIZE", Config.FLATTEN_SIZE),
              ("TIME_STEPS", Config.TIME_STEPS), ("NUM_CLASSES", Config.NUM_CLASSES)]
    for k, v in checks:
        if saved_cfg.get(k) != v:
            print(f"  ⚠ {k}: ckpt={saved_cfg.get(k,'?')} vs config={v}")

    model = KWS_SNN_Tiny()
    model.load_state_dict(ckpt["model_state"])
    model.eval()
    sd = model.state_dict()

    print("\n=== Layer sizes ===")
    total = 0
    for k, v in sd.items():
        n = v.numel(); total += n
        print(f"  {k:45s} {str(list(v.shape)):25s} {n/1024:.2f} KB")
    print(f"\n  Tổng int8 : {total/1024:.1f} KB")
    print(f"  Val acc   : {ckpt.get('val_acc', 0):.4f}")

    # Đọc scalar params
    beta1      = float(sd.get("rlif1.beta",      torch.tensor(Config.BETA)).item())
    beta2      = float(sd.get("rlif2.beta",      torch.tensor(Config.BETA)).item())
    thresh1    = float(sd.get("rlif1.threshold", torch.tensor(1.0)).item())
    thresh2    = float(sd.get("rlif2.threshold", torch.tensor(1.0)).item())

    c1h = Config.MAX_LEN // 2;  c1w = Config.N_MELS // 2
    c2h = Config.MAX_LEN // 4;  c2w = Config.N_MELS // 4

    with open("model_weights.h", "w") as f:
        f.write("#pragma once\n")
        f.write("// AUTO-GENERATED by export_to_c.py\n")
        f.write(f"// Val accuracy : {ckpt.get('val_acc', 0):.4f}\n")
        f.write(f"// Labels       : {Config.ALL_LABELS}\n")
        f.write(f"// Architecture : CNN + RLIF (recurrent LIF)\n\n")
        f.write("#include <Arduino.h>\n\n")

        # Macros
        f.write(f"#define KWS_NUM_CLASSES   {Config.NUM_CLASSES}\n")
        f.write(f"#define KWS_TIME_STEPS    {Config.TIME_STEPS}\n")
        f.write(f"#define KWS_MAX_LEN       {Config.MAX_LEN}\n")
        f.write(f"#define KWS_N_MELS        {Config.N_MELS}\n")
        f.write(f"#define KWS_CONV1_CH      {Config.CONV1_CH}\n")
        f.write(f"#define KWS_CONV2_CH      {Config.CONV2_CH}\n")
        f.write(f"#define KWS_FC1_UNITS     {Config.FC1_UNITS}\n")
        f.write(f"#define KWS_FLATTEN_SIZE  {Config.FLATTEN_SIZE}\n")
        f.write(f"#define KWS_CONV1_OUT_H   {c1h}\n")
        f.write(f"#define KWS_CONV1_OUT_W   {c1w}\n")
        f.write(f"#define KWS_CONV2_OUT_H   {c2h}\n")
        f.write(f"#define KWS_CONV2_OUT_W   {c2w}\n\n")

        # RLIF scalars — beta và threshold đã học
        write_scalar("RLIF1_BETA",      beta1,   f)
        write_scalar("RLIF2_BETA",      beta2,   f)
        write_scalar("RLIF1_THRESHOLD", thresh1, f)
        write_scalar("RLIF2_THRESHOLD", thresh2, f)
        f.write("\n")
        print(f"\n  rlif1: beta={beta1:.4f}  threshold={thresh1:.4f}")
        print(f"  rlif2: beta={beta2:.4f}  threshold={thresh2:.4f}")

        # Labels
        f.write("static const char* KWS_LABELS[] = {")
        f.write(", ".join(f'"{l}"' for l in Config.ALL_LABELS))
        f.write("};\n\n")

        # CNN weights
        write_tensor("conv1_weight", sd["conv1.weight"], f)
        write_tensor("conv1_bias",   sd["conv1.bias"],   f)
        write_tensor("bn1_weight",   sd["bn1.weight"],   f)
        write_tensor("bn1_bias",     sd["bn1.bias"],     f)
        write_tensor("bn1_mean",     sd["bn1.running_mean"], f)
        write_tensor("bn1_var",      sd["bn1.running_var"],  f)
        write_tensor("conv2_weight", sd["conv2.weight"], f)
        write_tensor("conv2_bias",   sd["conv2.bias"],   f)
        write_tensor("bn2_weight",   sd["bn2.weight"],   f)
        write_tensor("bn2_bias",     sd["bn2.bias"],     f)
        write_tensor("bn2_mean",     sd["bn2.running_mean"], f)
        write_tensor("bn2_var",      sd["bn2.running_var"],  f)

        # FC weights
        write_tensor("fc1_weight", sd["fc1.weight"], f)
        write_tensor("fc1_bias",   sd["fc1.bias"],   f)
        write_tensor("fc2_weight", sd["fc2.weight"], f)
        write_tensor("fc2_bias",   sd["fc2.bias"],   f)

        # RLIF1 recurrent weights — V·S[t] trong all_to_all Linear
        write_tensor("rlif1_rec_weight", sd["rlif1.recurrent.weight"], f)
        write_tensor("rlif1_rec_bias",   sd["rlif1.recurrent.bias"],   f)

        # RLIF2 recurrent weight — elementwise V (all_to_all=False)
        write_tensor("rlif2_V", sd["rlif2.V"], f)

    print(f"\n✓ Xuất xong: model_weights.h")
    print("  Copy vào thư mục sketch kws_esp32/")


if __name__ == "__main__":
    export()